--- 
  addons: 
    apt: 
      packages: 
        - postgresql-10
        - postgresql-client-10
    postgresql: "10"
  after_script: 
    - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESUL"
  after_success: "yarn coverage"
  before_install: 
    - "sudo cp /etc/postgresql/{9.6,10}/main/pg_hba.conf"
    - "sudo /etc/init.d/postgresql restart"
  before_script: 
    - "psql -c 'create database testdb;' -U postgres"
    - "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter"
    - "chmod +x ./cc-test-reporter"
    - "./cc-test-reporter before-build"
  cache: 
    directories: 
      - node_modules
  env: 
    global: 
      - CC_TEST_REPORTER_ID=729ee931e2880149e6d9f633fe704b87a931e64d9810a2be1b27e7940c7eb95f
  install: yarn
  language: node_js
  matrix: 
    include: 
      - 
        node_js: "12"
  script: 
    - "yarn test"
  services: 
    - postgresql
  